name: Deploy_db_v2

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

env:
  AWS_REGION_NAME: "eu-central-1"

jobs:

  CI_part:
    env:
      DUMP_NAME: rocinante.routine.sql.bz
      DUMP_NAME_ONLY: rocinante.routine.sql
      DRUPAL_DB: ${{ secrets.MYSQL_DRUPAL_DB }}
    
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GH_ACTION_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GH_ACTION_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
    
    - name: Get Variables
      run: |
        IP_ADDRESS=`aws ec2 describe-instances --filters "Name=tag:Name,Values=rocinante" --query "Reservations[*].Instances[*].{IP:PublicIpAddress}" --output text | grep -E "([0-9]{1,3}[\.]){3}[0-9]{1,3}$"`
        echo "$IP_ADDRESS"
        echo "IP_ADDRESS=$IP_ADDRESS" >> $GITHUB_ENV
    
    - name: Test
      run: echo ${{ env.IP_ADDRESS }}
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.IP_ADDRESS }}
        username: ec2-user
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "db/${{ env.DUMP_NAME }}"
        target: "/home/ec2-user"
        strip_components: 1
    
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.IP_ADDRESS }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo mysql --connect-expired-password -u${{ secrets.MYSQL_ADMIN_USER }} -p${{ secrets.MYSQL_ADMIN_USER_PASS }} -e "DROP DATABASE IF EXISTS ${{ env.DRUPAL_DB }};"
          sudo mysql --connect-expired-password -u${{ secrets.MYSQL_ADMIN_USER }} -p${{ secrets.MYSQL_ADMIN_USER_PASS }} -e "CREATE DATABASE ${{ env.DRUPAL_DB }} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
          sudo bunzip2 /home/ec2-user/${{ env.DUMP_NAME }}
          sudo mysql --connect-expired-password -u${{ secrets.MYSQL_ADMIN_USER }} -p${{ secrets.MYSQL_ADMIN_USER_PASS }} -A -D $DRUPAL_DB < /home/ec2-user/${{ env.DUMP_NAME_ONLY }}
          sudo rm -f /home/ec2-user/${{ env.DUMP_NAME_ONLY }} 
