name: example_database

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

env:
  AWS_REGION_NAME: "eu-central-1"

jobs:

  Database:

    env:
      DB_DUMP_NAME: rocinante_db_220503.sql.bz
      DB_DUMP_NAME_ONLY: rocinante_db_220503.sql

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GH_ACTION_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GH_ACTION_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}

    - name: Deploy site database
      run: |
        IP_ADDRESS=`aws ec2 describe-instances --filters Name=tag:Name,Values=rocinante Name=instance-state-name,Values=running --query "Reservations[*].Instances[*].{IP:PublicIpAddress}" --output text`
        echo "${{ secrets.SSH_KEY }}" > ssh_key.key
        chmod 0600 ssh_key.key
        ssh -i ssh_key.key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ec2-user@$IP_ADDRESS "sudo mysql --connect-expired-password -u${{ secrets.MYSQL_ADMIN_USER }} -p${{ secrets.MYSQL_ADMIN_USER_PASS }} -e 'DROP DATABASE IF EXISTS ${{ secrets.MYSQL_DRUPAL_DB }}';"
        ssh -i ssh_key.key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ec2-user@$IP_ADDRESS "sudo mysql --connect-expired-password -u${{ secrets.MYSQL_ADMIN_USER }} -p${{ secrets.MYSQL_ADMIN_USER_PASS }} -e 'CREATE DATABASE ${{ secrets.MYSQL_DRUPAL_DB }} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';"
        ssh -i ssh_key.key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ec2-user@$IP_ADDRESS sudo bunzip2 /home/ec2-user/data/${{ env.DB_DUMP_NAME }}
        ssh -i ssh_key.key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ec2-user@$IP_ADDRESS "sudo mysql --connect-expired-password -u${{ secrets.MYSQL_ADMIN_USER }} -p${{ secrets.MYSQL_ADMIN_USER_PASS }} -A -D ${{ secrets.MYSQL_DRUPAL_DB }} < /home/ec2-user/data/${{ env.DB_DUMP_NAME_ONLY }}"
