name: Test

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main

jobs:

  CI_part:
    
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    
    - name: Sync
      run: |
        echo "${{ secrets.CONFIG_IN_PHP }}" > config.in.php
        echo "${{ secrets.DB_CONFIG_ADD }}" >> config.in.php
        cat config.in.php
